### ISSUE TITLE
how to more easily reference other resources other than by UUID?

### ISSUE THREAD

**Issue by ckhordiasma** [appgate/sdp-operator#164]
When trying to use the operator I run into a lot of cases where I have to reference another resource by UUID, like in the identity-provider resource below referencing ip pools
```
apiVersion: beta.appgate.com/v1
kind: IdentityProvider-v15
metadata:
  name: local
spec:
... etc ...
  ipPoolV4: XXXXXX
  ipPoolV6: XXXXXX
  name: local
  notes: Built-in Identity Provider on local database.
  tags:
  - builtin
  type: LocalDatabase
```

is there a better way that I can reference other resources, such as by resource name?
